# Custom Keybindings Override
unbind = SUPER, W
bindd = SUPER, Q, Close window, killactive

unbind = SUPER, RETURN
bindd = SUPER, RETURN, Terminal, exec, ghostty

unbind = SUPER, Z
bindd = SUPER, Z, Zen Browser, exec, zen-browser --new-window

unbind = SUPER, G
bindd = SUPER, G, GitHub, exec, zen-browser --new-window "https://github.com"

unbind = SUPER, Y
bindd = SUPER, Y, YouTube, exec, zen-browser --new-window "https://youtube.com"

unbind = SUPER, C
bindd = SUPER, C, Visual Studio Code, exec, code --disable-gpu --enable-features=UseOzonePlatform --ozone-platform=wayland

unbind = SUPER, W
bindd = SUPER, W, WhatsApp, exec, zen-browser --new-window "https://web.whatsapp.com"

unbind = SUPER SHIFT, F
bindd = SUPER, E, File Explorer, exec, uwsm-app -- nautilus --new-window

unbind = SUPER, N
bindd = SUPER, N, Netflix, exec, netflix

# Input Override
input {
  touchpad {
    natural_scroll = true
  }
}

# LooknFeel
general {
  border_size = 0
}
